name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Frontend
      run: cd ./vuser-frontend && docker build . --file Dockerfile --tag frontend:$(date +%s)
    - name: Build the API
      run: cd ./vuser-api && docker build . --file Dockerfile --tag frontend:$(date +%s)
